### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by MarcusNordstrom** [db0company/List#4]
Hi,
We would like to use your list inside our project!
But due to the fact that there is no licence, we are not allowed to use it.
We would be very grateful for the time saved by using yours instead of writing our own.
MIT Licence is recommended for most projects, if you want to choose another one, look at
[https://choosealicense.com/](https://choosealicense.com/)

**Comment by db0company** [comment]
That'd be my license: http://www.wtfpl.net/
Go wild!
